version: '3'
services:
  frontend:
    build: 
      context: ./frontend
    environment:
      - BACKEND_URL=http://localhost:5000
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/todoapp
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
